---
version: "2.3"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - heimdall_data:/config
#    ports:
#      - 80:80
#      - 443:443
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.heimdall-secure.rule=Host(`heimdall.poc.ccado.fr`)"
      - "traefik.http.routers.heimdall-secure.entrypoints=websecure"
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"

volumes:
  heimdall_data:

networks:
  traefik-proxy:
    external: true
