api:
  dashboard: true

entryPoints:
  udp5001:
    address: :5001/udp

  tcp5001:
    address: :5001/tcp

  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: :443
    http:
      middlewares:
        - secureHeaders@file
      tls:
        certResolver: letsencrypt

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /configurations/dynamic.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email: ccado@free.fr
      storage: acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web
