version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: ieKeta7peeX4Raif4the
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    networks:
      - traefik-proxy
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: ieKeta7peeX4Raif4the
      DB_NAME: wiki
    restart: unless-stopped
#    ports:
#      - "80:3000"
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.wikijs-secure.rule=Host(`wiki.poc.ccado.fr`)"
      - "traefik.http.routers.wikijs-secure.entrypoints=websecure"
      - "traefik.http.services.wikijs.loadbalancer.server.port=3000"

volumes:
  db-data:

networks:
  traefik-proxy:
    external: true
